### PR TITLE
docs: versioned docs

### PR DESCRIPTION
**Pull request by jbinda**
### Summary

Cherry-picked versioned docs from V2 + add version dropdown

### CODE REVIEW

**Comment by jbinda** [comment]
still need to handle links from footer docs - that's why CI fails

**Review by thymikee — APPROVED** [review]
As a next step let's add Algolia search here :) You'll need to apply for it, following the docs on Docusaurus site

**Comment by thymikee** [comment]
CI says "Error: Docusaurus found broken links"

**Comment by jbinda** [comment]
> CI says "Error: Docusaurus found broken links"

yes, it's because:
- footer doesn't handle versioning (I removed path: 3x from config to fallback to most recent docs in that case) - ideally we would like to have generic page in footer that shows main page with proper sidebar
- v2 of docs has `React Native API` and `Node API` in navbar while V3 has only `API`

**Comment by jbinda** [comment]
I have fixed all links to versioned docs in v2. Thanks for review !

**Review by thymikee — APPROVED** [review]

**Pull request merged**
