### PR TITLE
fix: Listen on [::] or 0.0.0.0 by default

### PR DESCRIPTION
**Pull request by jinliming2**
### Summary

See #261

### CODE REVIEW

**Comment by jbinda** [comment]
hi @jinliming2 thank you for the PR - going to review it soon

**Review by RafikiTiki — APPROVED** [review]

**Comment by RafikiTiki** [comment]
Hi @jinliming2 would you be able to rebase this branch on top of `main` and generate changeset for this PR?

**Comment by jinliming2** [comment]
@RafikiTiki done.

**Comment by jbroma** [comment]
Leaving this as closed - in `v4` we have upgraded `fastify` to newest version and this change is already included there.

**Pull request closed without merging**
