### PR TITLE
fix: `@expo` changed to `expo` in babel-loader config in webpack config templates

### PR DESCRIPTION
**Pull request by outsung**
### Summary

When using expo library or when using expo and repack,
Need to modify it to `expo` instead of `@expo` to work.

Can refer to this [comment](https://github.com/callstack/repack/issues/304#issuecomment-1809708696).

### CODE REVIEW

**Comment by RafikiTiki** [comment]
Hey @outsung! First of all – thanks for your contribution!

I think the `@expo` regex was there for a reason – there are still some expo packages that are named `@expo/package-name` (for example: https://www.npmjs.com/package/@expo/vector-icons), and I think they still need to be processed by webpack. Let me ask around and see if we would like to leave the old `@expo` rule along with the new `@expo` one for backward compatibility.

**Comment by outsung** [comment]
@RafikiTiki Thanks for the confirmation!

**Comment by jbroma** [comment]
@RafikiTiki any update on this?

**Comment by RafikiTiki** [comment]
Thanks for pinging me – from my investigation, it looks like only the [@expo/vector-icons]( https://www.npmjs.com/package/@expo/vector-icons) package uses the `@expo` naming convention. I think we're good to remove it from the default webpack config since we're not using this package internally.

If anyone would want to use it, it can be added to the webpack config same as with other 3rd party packages that need to be transpiled by babel.

**Review by RafikiTiki — APPROVED** [review]

**Review by jbroma — APPROVED** [review]
LGTM

**Comment by jbroma** [comment]
Thanks for your contribution @outsung!

**Pull request merged**
